### PR TITLE
add test to cover case where interface has a "this" property and a type literal

### PR DESCRIPTION
**Pull request by Pmyl**
This shows that #88 is not relevant, let me know if I'm doing anything wrong here

### CODE REVIEW

**Comment by uittorio** [comment]
Yeah, I think I forgot to write the scenario correctly. There is definitely an issue. Did you try instead

```ts 

interface Test {
 a: { b: 2}
 c: this
}
```

**Comment by Pmyl** [comment]
Interesting, the build fails when the "this" property is declared after the type literal... I'll update the test and work on it

**Comment by Pmyl** [comment]
Done, this is now ready for review @uittorio

**Comment by uittorio** [comment]
thanks!!!! I hope it was not too difficult to find the issue!

**Comment by uittorio** [comment]
if you merge remember to use something like this, so it will appear on the changeling
 
fix(this): make sure literal type will not interfere with "this" reference

**Pull request merged**
